 # Dataset parameters (paths with image, and path to ground truth files)
dataset:
  # Train ground truth & dir
  gt_path: "../input/dataset/train_ship_segmentations_v2.csv"
  train_dir: "../input/dataset/train_v2"
  # Test dir
  test_dir: "../input/dataset/test_v2"

# Output paths for results
output:
  graph_results: "../output/results/graph_results.png"
  original: "../output/results/original.png"
  with_mask: "../output/results/segmented.png"

# Model parameters for saving entire model or them weights
model:
  # Trained model save paths
  entire_path: "../models/trained/model/"
  weights_path: "../models/trained/weights/"
  files:
    # Model save path
    entire: "asd_model"
    h5: "asd_model.h5"
    # Weights save path
    weights: "asd_weights"
  # Checkpoint paths
  ckpt_paths:
    # Save path
    entire: "../models/checkpoint/model/cp.ckpt"
    # Weight path
    weights: "../models/checkpoint/weights/cp.ckpt"

# Preprocess default parameters
preprocess:
  image_size: [160, 160]
  color_channels: 3
  batch_size: 22

# Hyperparameters
hyper:
  epochs: 10
  initial_epoch: 0
  # Learning rate
  lr_rate: 0.001

# Prediction
prediction:
  predict_batch_number: 1
  predict_image_number: 15 # <=31
